// Code generated by mockery v1.0.0
package mocks

import ast "github.com/opsidian/parsley/ast"
import mock "github.com/stretchr/testify/mock"

// NodeBuilder is an autogenerated mock type for the NodeBuilder type
type NodeBuilder struct {
	mock.Mock
}

// BuildNode provides a mock function with given fields: _a0
func (_m *NodeBuilder) BuildNode(_a0 []ast.Node) ast.Node {
	ret := _m.Called(_a0)

	var r0 ast.Node
	if rf, ok := ret.Get(0).(func([]ast.Node) ast.Node); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ast.Node)
		}
	}

	return r0
}
