version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.17
    working_directory: /go/src/github.com/conflowio/parsley
    steps:
      - checkout
      - run: make check
      - run: make test

workflows:
  version: 2
  test:
    jobs:
      - test
