// Code generated by counterfeiter. DO NOT EDIT.
package parsleyfakes

import (
	"sync"

	"github.com/opsidian/parsley/data"
	"github.com/opsidian/parsley/parsley"
)

type FakeParser struct {
	ParseStub        func(ctx *parsley.Context, leftRecCtx data.IntMap, pos parsley.Pos) (parsley.Node, data.IntSet, parsley.Error)
	parseMutex       sync.RWMutex
	parseArgsForCall []struct {
		ctx        *parsley.Context
		leftRecCtx data.IntMap
		pos        parsley.Pos
	}
	parseReturns struct {
		result1 parsley.Node
		result2 data.IntSet
		result3 parsley.Error
	}
	parseReturnsOnCall map[int]struct {
		result1 parsley.Node
		result2 data.IntSet
		result3 parsley.Error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeParser) Parse(ctx *parsley.Context, leftRecCtx data.IntMap, pos parsley.Pos) (parsley.Node, data.IntSet, parsley.Error) {
	fake.parseMutex.Lock()
	ret, specificReturn := fake.parseReturnsOnCall[len(fake.parseArgsForCall)]
	fake.parseArgsForCall = append(fake.parseArgsForCall, struct {
		ctx        *parsley.Context
		leftRecCtx data.IntMap
		pos        parsley.Pos
	}{ctx, leftRecCtx, pos})
	fake.recordInvocation("Parse", []interface{}{ctx, leftRecCtx, pos})
	fake.parseMutex.Unlock()
	if fake.ParseStub != nil {
		return fake.ParseStub(ctx, leftRecCtx, pos)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fake.parseReturns.result1, fake.parseReturns.result2, fake.parseReturns.result3
}

func (fake *FakeParser) ParseCallCount() int {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	return len(fake.parseArgsForCall)
}

func (fake *FakeParser) ParseArgsForCall(i int) (*parsley.Context, data.IntMap, parsley.Pos) {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	return fake.parseArgsForCall[i].ctx, fake.parseArgsForCall[i].leftRecCtx, fake.parseArgsForCall[i].pos
}

func (fake *FakeParser) ParseReturns(result1 parsley.Node, result2 data.IntSet, result3 parsley.Error) {
	fake.ParseStub = nil
	fake.parseReturns = struct {
		result1 parsley.Node
		result2 data.IntSet
		result3 parsley.Error
	}{result1, result2, result3}
}

func (fake *FakeParser) ParseReturnsOnCall(i int, result1 parsley.Node, result2 data.IntSet, result3 parsley.Error) {
	fake.ParseStub = nil
	if fake.parseReturnsOnCall == nil {
		fake.parseReturnsOnCall = make(map[int]struct {
			result1 parsley.Node
			result2 data.IntSet
			result3 parsley.Error
		})
	}
	fake.parseReturnsOnCall[i] = struct {
		result1 parsley.Node
		result2 data.IntSet
		result3 parsley.Error
	}{result1, result2, result3}
}

func (fake *FakeParser) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeParser) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ parsley.Parser = new(FakeParser)
