// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import parser "github.com/opsidian/parsley/parser"

// FuncFactory is an autogenerated mock type for the FuncFactory type
type FuncFactory struct {
	mock.Mock
}

// CreateParser provides a mock function with given fields:
func (_m *FuncFactory) CreateParser() parser.Func {
	ret := _m.Called()

	var r0 parser.Func
	if rf, ok := ret.Get(0).(func() parser.Func); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(parser.Func)
		}
	}

	return r0
}
