// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Position is an autogenerated mock type for the Position type
type Position struct {
	mock.Mock
}

// Filename provides a mock function with given fields:
func (_m *Position) Filename() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Pos provides a mock function with given fields:
func (_m *Position) Pos() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// String provides a mock function with given fields:
func (_m *Position) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
